sonar.projectKey=eularix_ciph
sonar.projectName=Ciph
sonar.projectVersion=2.0.0
sonar.organization=eularix

sonar.sources=modules/ciph-go

sonar.go.coverage.reportPaths=modules/ciph-go/coverage.out

sonar.exclusions=**/vendor/**,**/*_test.go,**/mocks/**,**/example/**,**/docs/**
sonar.coverage.exclusions=**/vendor/**,**/*_test.go,**/example/**,**/docs/**

sonar.cpd.exclusions=**/*_test.go

sonar.tests=modules/ciph-go
sonar.test.inclusions=**/*_test.go

sonar.links.homepage=https://github.com/Eularix/ciph
sonar.links.ci=https://github.com/Eularix/ciph/actions
sonar.links.issue=https://github.com/Eularix/ciph/issues
sonar.links.scm=https://github.com/Eularix/ciph
